from episodate import episodate

ed = episodate()
print(ed.search('the owl house'))
show = ed.show('the-owl-house')
print(show.name)
print(show.description)
print(show.start_date)
print(show.country)
print(show.status)
print(show.runtime)
print(show.network)
print(show.genres)
print(show.rating)
print(show.countdown)
print(show.episodes)
print(type(show.countdown))
print(ed.popular())
print(len(ed.popular()))
